version: '3.6'

volumes:
  database:
    external:
      name: ${PROJECT_NAME}_mysql

services:
  mysql:
    restart: always
    image: lscr.io/linuxserver/mariadb:${DB_VERSION}
    container_name: ${PROJECT_NAME}_mysql
    volumes:
      - ./mysql/dev.cnf:/etc/mysql/conf.d/dev.cnf
      - ./mysql/remote-access.cnf:/etc/mysql/conf.d/remote-access.cnf
      - ./mysql/performance-schema.cnf:/etc/mysql/conf.d/performance-schema.cnf
      - database:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}

  phpmyadmin:
    depends_on:
      - mysql
    image: lscr.io/linuxserver/phpmyadmin:${PMA_VERSION}
    container_name: ${PROJECT_NAME}_phpmyadmin
    restart: always
    ports:
      - "${PMA_PORT}:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      HOST_IP: ${HOST_IP}