version: '3.6'

volumes:
  database:
    name: ${PROJECT_NAME}_mysql

services:
  mysql:
    restart: always
    image: lscr.io/linuxserver/mariadb:${DB_VERSION}
    container_name: ${PROJECT_NAME}_mysql
    volumes:
      - ./mysql/dev.cnf:/etc/mysql/conf.d/dev.cnf
      - ./mysql/remote-access.cnf:/etc/mysql/conf.d/remote-access.cnf
      - ./mysql/performance-schema.cnf:/etc/mysql/conf.d/performance-schema.cnf
      - ./mysql/config:/config
      - database:/config/databases
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      TZ: Europe/Berlin

  phpmyadmin:
    depends_on:
      - mysql
    image: lscr.io/linuxserver/phpmyadmin:${PMA_VERSION}
    container_name: ${PROJECT_NAME}_phpmyadmin
    restart: always
    ports:
      - "${PMA_PORT}:80"
    environment:
      PMA_HOST: ${PROJECT_NAME}_mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      HOST_IP: ${DOCKER_HOST_IP}